UserAwards/UserAwards/Models/Entity/PersonLinkAward.cs
using System;

namespace UserAwards.Models.Entity
{
	/// <summary>
	/// The class PersonLinkAward.
	/// </summary>
	public class PersonLinkAward
	{
		/// <summary>
		/// The Person id.
		/// </summary>
		public Guid PersonId { get; set; }

		/// <summary>
		/// The Award id.
		/// </summary>
		public Guid AwardId { get; set; }
	}
}

UserAwards/UserAwards/Models/Helpers/PersonLinkAwardHelper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using UserAwards.Models.Entity;

namespace UserAwards.Models.Helpers
{
	public static class PersonLinkAwardHelper
	{
		private static List<PersonLinkAward> _personLinkAwardList;

		/// <summary>
		/// The collection peron
		/// </summary>
		private static List<PersonLinkAward> PersonLinkAwardList
		{
			get { return _personLinkAwardList ?? (_personLinkAwardList = GetPersonList()); }
		}

		/// <summary>
		/// Gets award listItem.
		/// </summary>
		public static PersonLinkAwardModel NewAttachAward()
		{
			var personLinkAwardModel = new PersonLinkAwardModel();
			return personLinkAwardModel;
		}

		/// <summary>
		/// Gets award listItem.
		/// </summary>
		public static List<SelectListItem> AwardModelListItem()
		{
			return AwardHelper.AwardModelList.Select(_ => new SelectListItem { Text = _.Title, Value = _.Id.ToString() }).ToList();
		}

		/// <summary>
		/// Gets person listItem.
		/// </summary>
		public static List<SelectListItem> PersonModelListItem()
		{
			return PersonHelper.PersonModelList.Select(_ => new SelectListItem {Text = _.Name, Value = _.Id.ToString()}).ToList();
		}

		/// <summary>
		/// Gets person link award list.
		/// </summary>
		/// <returns></returns>
		public static List<PersonLinkAwardModel> GetPersonLinkAwardList()
		{
			return PersonLinkAwardList.Select(item => new PersonLinkAwardModel
			{
				PersonModelData = PersonHelper.GetPersonModelEntity(item.PersonId), AwardModelData = AwardHelper.GetAwardModelEntity(item.AwardId)
			}).ToList();
		}


		/// <summary>
		/// Gets PersonLinkAward collection.
		/// </summary>
		/// <returns></returns>
		private static List<PersonLinkAward> GetPersonList()
		{
			var personLinkAwardList = new List<PersonLinkAward>
			{
				new PersonLinkAward {PersonId = Guid.Parse("7816ec31-2185-4e0f-a32c-64d970eff4d5"), 
								AwardId = Guid.Parse("7816ec31-2185-4e0f-a32c-64d970eff001"), },
				new PersonLinkAward {PersonId = Guid.Parse("7816ec31-2185-4e0f-a32c-64d970eff4d5"), 
								AwardId = Guid.Parse("7816ec31-2185-4e0f-a32c-64d970eff002"), },
				new PersonLinkAward {PersonId = Guid.Parse("7816ec31-2185-4e0f-a32c-64d970eff4d7"), 
								AwardId = Guid.Parse("7816ec31-2185-4e0f-a32c-64d970eff003"), },
			};
			return personLinkAwardList;
		}

		public static void AddAwardToPerson(PersonLinkAwardModel model)
		{
			var personLinkAward = new PersonLinkAward
			{
				PersonId = model.PersonId,
				AwardId = model.AwardId
			};

			PersonLinkAwardList.Add(personLinkAward);
		}

		public static void DeeteAttachedAward(Guid personId, Guid awardId)
		{
			var deleteItem = PersonLinkAwardList.FirstOrDefault(_ => _.PersonId == personId && _.AwardId == awardId);
			if (deleteItem != null)
			{
				PersonLinkAwardList.Remove(deleteItem);
			}
		}
	}
}

UserAwards/UserAwards/Controllers/AwardController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using UserAwards.Models;
using UserAwards.Models.Helpers;

namespace UserAwards.Controllers
{
	public class AwardController : Controller
	{

		[Route("awards")]
		public ActionResult AwardsList()
		{
			return View("Index",AwardHelper.AwardModelList);
		}

		[Route("awards/{userName}")]
		public ActionResult IndexByUser(string userName)
		{
			var res = PersonLinkAwardHelper.GetPersonLinkAwardList()
				.Where(_ => _.PersonModelData.Name == userName)
				.Select(_ => _.AwardModelData)
				.ToList();
			return View("Index", res);
		}

		[Route("award/{userId:guid}")]
		public ActionResult AwawrdById(Guid userId)
		{
			return View("Details", AwardHelper.GetAwardModelEntity(userId));
		}

		[Route("award/{id}/edit")]
		public ActionResult EditAward(Guid id)
		{
			return View("Edit", AwardHelper.GetAwardModelEntity(id));
		}

		[Route("award/{id}/delete")]
		public ActionResult DeleteAward(Guid id)
		{
			return View("Delete", AwardHelper.GetAwardModelEntity(id));
		}

		[Route("create-award")]
		public ActionResult CreateAward()
		{
			return View("Create");
		}

		[OutputCache(Duration = 30, Location = OutputCacheLocation.Downstream)]
		[Authorize(Roles = "Admin, User")]
		public ActionResult Index()
		{
			return View(AwardHelper.AwardModelList);
		}


		public ActionResult Details(Guid id)
		{
			return View(AwardHelper.GetAwardModelEntity(id));
		}

		public ActionResult Create()
		{
			return View("Create");
		}

		public ActionResult Edit(Guid id)
		{
			return View(AwardHelper.GetAwardModelEntity(id));
		}

		[HttpPost]
		public ActionResult Create(AwardModel model, HttpPostedFileBase image = null)
		{
			try
			{
				if (image != null)
				{
					model.ImageMimeType = image.ContentType;
					model.ImageData = new byte[image.ContentLength];
					image.InputStream.Read(model.ImageData, 0, image.ContentLength);

					ModelState.Remove("ImageData");
					ModelState.Add("ImageData", new ModelState());
					ModelState.SetModelValue("ImageData", new ValueProviderResult(new byte[image.ContentLength], "1", null));
				}


				if (!ModelState.IsValid)
				{
					return View();
				}

				AwardHelper.CreateEntity(model);
				return RedirectToAction("Index");
			}
			catch
			{
				return View();
			}
		}

		public ActionResult Delete(Guid id)
		{
			return View(AwardHelper.GetAwardModelEntity(id));
		}

		public FileContentResult GetImage(Guid id)
		{

			var entity = AwardHelper.GetAwardModelEntity(id);

			if (entity != null && entity.ImageData != null && entity.ImageMimeType != null)
			{
				return File(entity.ImageData, entity.ImageMimeType);
			}

			return null;
		}

		[HttpPost]
		public ActionResult Edit(AwardModel model, HttpPostedFileBase image = null)
		{
			try
			{
					if (image != null)
				{
					model.ImageMimeType = image.ContentType;
					model.ImageData = new byte[image.ContentLength];
					image.InputStream.Read(model.ImageData, 0, image.ContentLength);
				}

				if (ModelState.IsValid)
				{
					AwardHelper.UpdateEntity(model);
				}
				return RedirectToAction("Index");
			}
			catch
			{
				return View();
			}
		}

		[HttpPost]
		public ActionResult Delete(AwardModel model)
		{
			try
			{
				AwardHelper.DeleteEntity(model.Id);
				return RedirectToAction("Index");
			}
			catch
			{
				return View();
			}
		}

		
		public ActionResult AwawrdByName(string awardName)
		{
			return View("Details", AwardHelper.AwardModelList.FirstOrDefault(_ => _.Title == awardName));
		}
	}
}

UserAwards/UserAwards/Controllers/PersonLinkAwardController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using UserAwards.Models;
using UserAwards.Models.Helpers;

namespace UserAwards.Controllers
{
	public class PersonLinkAwardController : Controller
	{

		[Authorize(Roles = "Admin")]
		public ActionResult Index()
		{
			return View(PersonLinkAwardHelper.GetPersonLinkAwardList());
		}


		[HttpPost]
		public ActionResult AttachedAward(PersonLinkAwardModel model)
		{
			if (!ModelState.IsValid)
			{
				return View("NewAttachAward");
			}

			PersonLinkAwardHelper.AddAwardToPerson(model);
			return RedirectToAction("Index");
		}

		public ActionResult ModalAction(string id)
		{
			return PartialView("_ModalContentPartial", AwardHelper.GetAwardById(Guid.Parse(id)));
		}

		public ActionResult NewAttachAward()
		{
			ViewBag.PersonModelListItem = PersonLinkAwardHelper.PersonModelListItem();
			ViewBag.AwardModelListItem = PersonLinkAwardHelper.AwardModelListItem();
			return View(PersonLinkAwardHelper.NewAttachAward());
		}

		public ActionResult Delete(Guid personId, Guid awardId)
		{

			PersonLinkAwardHelper.DeeteAttachedAward(personId, awardId);
			return RedirectToAction("Index");
		}

		public ActionResult CheckAwardDuplicate(PersonLinkAwardModel personLinkAwardModel)
		{
			var currentList = PersonLinkAwardHelper.GetPersonLinkAwardList();

			if (currentList.Any(_ => _.AwardModelData.Id == personLinkAwardModel.AwardId && _.PersonModelData.Id == personLinkAwardModel.PersonId))
			{
				return Json(false, JsonRequestBehavior.AllowGet);
			}
			return Json(true, JsonRequestBehavior.AllowGet);
		}
	}
}

UserAwards/UserAwards/Views/PersonLinkAward/Index.cshtml
@model IEnumerable<UserAwards.Models.PersonLinkAwardModel>

@{
	ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
	@Html.ActionLink("New", "NewAttachAward")
</p>


<script type="text/javascript">
		$(document).ready(function () {
			$(function () {
				$('body').on('click', '.img-thumbnail',
					function (e) {
					var btn = $(e.target);
					var url = "/PersonLinkAward/ModalAction/";
						var awardId = btn.data('awardid');
						$.post(url, {id:awardId})
						.done(function(response) {
							$("#listOfCustomers").html(response);
							$('#listOfCustomers .modal').modal({});
						})
						.fail(function() {
							alert("error");
						});
				});
			});
		});
</script>


<div  id="listOfCustomers">
</div>

	<table>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.PersonModelData.Name)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.PersonModelData.Birthdate)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.PersonModelData.Age)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.AwardModelData.Title)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.AwardModelData.Description)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.AwardModelData.ImageData)
			</th>
		</tr>

		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.PersonModelData.Name)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.PersonModelData.Birthdate)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.PersonModelData.Age)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.AwardModelData.Title)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.AwardModelData.Description)
				</td>
				<td>


					<img class="img-thumbnail"
						 width="30" height="30"
						 title="@item.AwardModelData.Title"
						 data-AwardId="@item.AwardModelData.Id"
						 src="@Url.Action("GetImage", "Award", new {item.AwardModelData.Id})" />

				</td>
			</tr>
		}
	</table>

UserAwards/UserAwards/Views/PersonLinkAward/NewAttachAward.cshtml
@model UserAwards.Models.PersonLinkAwardModel

@{
	ViewBag.Title = "Attach award";
}

<h2>Attach award</h2>


@using (Html.BeginForm("AttachedAward", "PersonLinkAward", FormMethod.Post, new { role = "form" }))
{
	@Html.AntiForgeryToken()
	@Html.ValidationSummary(true)

	<fieldset>
		<legend>Attach award</legend>

		<div class="form-group">
			@Html.Label("Person name")
			@Html.DropDownListFor(m => m.PersonId, (List<SelectListItem>)ViewBag.PersonModelListItem, "- Please select a Person -")
		</div>

		<div class="form-group">
			@Html.Label("Award")
			@Html.DropDownListFor(m => m.AwardId, (List<SelectListItem>)ViewBag.AwardModelListItem, "- Please select a Award -")
			@Html.ValidationMessageFor(m => m.AwardId)
		</div>

		<p>
			<input type="submit" value="Attach award" />
		</p>
	</fieldset>
}

<div>
	@Html.ActionLink("Back to List", "Index")
</div>

@*@section scripts
{
	@Scripts.Render("~/bundles/jqueryval")
}*@