UserAwards/UserAwards/Controllers/AwardController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using UserAwards.Models;
using UserAwards.Models.Helpers;

namespace UserAwards.Controllers
{
	public class AwardController : Controller
	{

		[Route("awards")]
		public ActionResult AwardsList()
		{
			return View("Index",AwardHelper.AwardModelList);
		}

		[Route("awards/{userName}")]
		public ActionResult IndexByUser(string userName)
		{
			var res = PersonLinkAwardHelper.GetPersonLinkAwardList()
				.Where(_ => _.PersonModelData.Name == userName)
				.Select(_ => _.AwardModelData)
				.ToList();
			return View("Index", res);
		}

		[Route("award/{userId:guid}")]
		public ActionResult AwawrdById(Guid userId)
		{
			return View("Details", AwardHelper.GetAwardModelEntity(userId));
		}

		[Route("award/{id}/edit")]
		public ActionResult EditAward(Guid id)
		{
			return View("Edit", AwardHelper.GetAwardModelEntity(id));
		}

		[Route("award/{id}/delete")]
		public ActionResult DeleteAward(Guid id)
		{
			return View("Delete", AwardHelper.GetAwardModelEntity(id));
		}

		[Route("create-award")]
		public ActionResult CreateAward()
		{
			return View("Create");
		}

		[OutputCache(Duration = 30, Location = OutputCacheLocation.Downstream)]
		[Authorize(Roles = "Admin, User")]
		public ActionResult Index()
		{
			return View(AwardHelper.AwardModelList);
		}


		public ActionResult Details(Guid id)
		{
			return View(AwardHelper.GetAwardModelEntity(id));
		}

		public ActionResult Create()
		{
			return View("Create");
		}

		public ActionResult Edit(Guid id)
		{
			return View(AwardHelper.GetAwardModelEntity(id));
		}

		[HttpPost]
		public ActionResult Create(AwardModel model, HttpPostedFileBase image = null)
		{
			try
			{
				if (image != null)
				{
					model.ImageMimeType = image.ContentType;
					model.ImageData = new byte[image.ContentLength];
					image.InputStream.Read(model.ImageData, 0, image.ContentLength);

					ModelState.Remove("ImageData");
					ModelState.Add("ImageData", new ModelState());
					ModelState.SetModelValue("ImageData", new ValueProviderResult(new byte[image.ContentLength], "1", null));
				}


				if (!ModelState.IsValid)
				{
					return View();
				}

				AwardHelper.CreateEntity(model);
				return RedirectToAction("Index");
			}
			catch
			{
				return View();
			}
		}

		public ActionResult Delete(Guid id)
		{
			return View(AwardHelper.GetAwardModelEntity(id));
		}

		public FileContentResult GetImage(Guid id)
		{

			var entity = AwardHelper.GetAwardModelEntity(id);

			if (entity != null && entity.ImageData != null && entity.ImageMimeType != null)
			{
				return File(entity.ImageData, entity.ImageMimeType);
			}

			return null;
		}

		[HttpPost]
		public ActionResult Edit(AwardModel model, HttpPostedFileBase image = null)
		{
			try
			{
					if (image != null)
				{
					model.ImageMimeType = image.ContentType;
					model.ImageData = new byte[image.ContentLength];
					image.InputStream.Read(model.ImageData, 0, image.ContentLength);
				}

				if (ModelState.IsValid)
				{
					AwardHelper.UpdateEntity(model);
				}
				return RedirectToAction("Index");
			}
			catch
			{
				return View();
			}
		}

		[HttpPost]
		public ActionResult Delete(AwardModel model)
		{
			try
			{
				AwardHelper.DeleteEntity(model.Id);
				return RedirectToAction("Index");
			}
			catch
			{
				return View();
			}
		}

		
		public ActionResult AwawrdByName(string awardName)
		{
			return View("Details", AwardHelper.AwardModelList.FirstOrDefault(_ => _.Title == awardName));
		}
	}
}

UserAwards/UserAwards/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using UserAwards.Models;
using UserAwards.Models.Helpers;

namespace UserAwards.Controllers
{
	public class PersonController : Controller
	{
		
		public ActionResult Index()
		{
			var fakeListPersonModel = (List<PersonModel>)Session["fakeListPersonModel"];


			var model = new List<PersonModel>();
			model.AddRange(PersonHelper.PersonModelList);

			if (fakeListPersonModel != null)
			{
				model.AddRange(fakeListPersonModel);
			}
			
			if (Request != null && Request.IsAjaxRequest())
			{
				return PartialView("_IndexListPartial", model);
			}
			return View(model);
		}

		public ActionResult IndexContaintsName(string userName)
		{
			return View("Index", PersonHelper.PersonModelList.Where(_=>_.Name.Contains(userName)));
		}

		public ActionResult Details(Guid id)
		{
			return View(PersonHelper.GetPersonModelEntity(id));
		}

		public ActionResult UserDetails(string userName)
		{
			return View("Details", PersonHelper.GetPersonModelEntity(userName).OrderBy(_=>_.Birthdate).FirstOrDefault());
		}

		public ActionResult DetailsById(string id)
		{
			return View("Details", PersonHelper.GetPersonModelEntity(Guid.Parse(id)));
		}

		public ActionResult Create()
		{
			return View("Create");
		}

		public FileStreamResult GetListPerson()
		{
			StringBuilder sb = new StringBuilder();
			foreach (var personItem in PersonHelper.PersonModelList)
			{
				var awardsIds =
					PersonLinkAwardHelper.GetPersonLinkAwardList()
						.Where(_ => _.PersonModelData.Id == personItem.Id)
						.Select(_ => _.AwardModelData.Id)
						.ToList();
				if (awardsIds.Any())
				{
					foreach (var itemawardsId in awardsIds)
					{
						sb.Append(string.Format("{0} {1} \r\n", personItem.Name, AwardHelper.GetAwardById(itemawardsId).Title));
					}
				}
				else
				{
					sb.Append(string.Format("{0} Наград нет \r\n", personItem.Name));
				}
			}

			var fs = new MemoryStream(Encoding.UTF8.GetBytes(sb.ToString()));
			return File(fs, "text/csv");
		}

		public ActionResult SaveNewPerson(PersonModel personModel)
		{
			Create(personModel);
			var model = PersonHelper.PersonModelList;
			return PartialView("_IndexListPartial", model);
		}

		[HttpPost]
		public ActionResult TemplateCreateNewPersonPartial()
		{
			return PartialView("_CreateNewPersonPartial");
		}

		[HttpPost]
		public ActionResult Create(PersonModel personModel, HttpPostedFileBase image = null)
		{
			if (image != null)
			{
				personModel.ImageMimeType = image.ContentType;
				personModel.ImageData = new byte[image.ContentLength];
				image.InputStream.Read(personModel.ImageData, 0, image.ContentLength);
			}

			var fakeListPersonModel = (List<PersonModel>)(Session["fakeListPersonModel"]) ?? new List<PersonModel>();
			fakeListPersonModel.Add(personModel);

			//todo
			Session["fakeListPersonModel"] = fakeListPersonModel;

			return RedirectToAction("Index");
		}

		public ActionResult ConfirmListCreate()
		{
			var fakeListPersonModel = (List<PersonModel>)Session["fakeListPersonModel"];
			if (fakeListPersonModel != null)
			{
				foreach (var personModel in fakeListPersonModel)
				{
					PersonHelper.CreateEntity(personModel);
				}
			}
			Session["fakeListPersonModel"] = null;
			var model = PersonHelper.PersonModelList;
			return PartialView("_IndexListPartial", model);
		}
		
		public ActionResult RevertListCreate()
		{
			Session["fakeListPersonModel"] = null;
			var model = PersonHelper.PersonModelList;
			return PartialView("_IndexListPartial", model);
		}

		public ActionResult Edit(Guid id)
		{
			if (PersonHelper.PersonModelList.All(_ => _.Id != id))
			{
				return HttpNotFound();
			}
			return View(PersonHelper.GetPersonModelEntity(id));
		}

		public ActionResult EditByUserId(string id)
		{
			return View("Edit", PersonHelper.GetPersonModelEntity(Guid.Parse(id)));
		}

		[HttpPost]
		public ActionResult Edit(PersonModel personModel, HttpPostedFileBase image = null)
		{
			try
			{
				if (image != null)
				{
					personModel.ImageMimeType = image.ContentType;
					personModel.ImageData = new byte[image.ContentLength];
					image.InputStream.Read(personModel.ImageData, 0, image.ContentLength);
				}

				PersonHelper.UpdateEntity(personModel);
				return RedirectToAction("Index");
			}
			catch
			{
				return View(PersonHelper.GetPersonModelEntity(personModel.Id));
			}
		}

		public FileContentResult GetImage(Guid id)
		{
			var entity = PersonHelper.GetPersonModelEntity(id);
			if (entity != null && entity.ImageData != null && entity.ImageMimeType != null)
			{
				return File(entity.ImageData, entity.ImageMimeType);
			}
			return null;
		}

		public ActionResult Delete(Guid id)
		{
			return View(PersonHelper.GetPersonModelEntity(id));
		}

		public ActionResult DeleteByUserId(string id)
		{
			return View("Delete", PersonHelper.GetPersonModelEntity(Guid.Parse(id)));
		}

		[HttpPost]
		public ActionResult DeletePerson(Guid id)
		{
			PersonHelper.DeleteEntity(id);
			var model = PersonHelper.PersonModelList;
			return PartialView("_IndexListPartial", model);
		}

		[HttpPost]
		public ActionResult Delete(PersonModel personModel)
		{
			try
			{
				PersonHelper.DeleteEntity(personModel.Id);
				return RedirectToAction("Index");
			}
			catch
			{
				return View();
			}
		}
	}
}

UserAwards/UserAwards/Controllers/UserManageController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using UserAwards.Models;

namespace UserAwards.Controllers
{
	public class UserManageController : Controller
	{

		[HttpPost]
		public ActionResult SaveDataUser(List<UserManageModel> list)
		{
			var userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();

			foreach (var item in list)
			{
				if (item.IsAdmin)
				{
					userManager.AddToRole(item.UserId, "Admin");
				}
				else
				{
					userManager.RemoveFromRole(item.UserId, "Admin");
				}
			}

			return RedirectToAction("Index", "PersonLinkAward");
		}

		[Authorize(Roles = "Admin")]
		public ActionResult Index()
		{
			ApplicationUserManager userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
			UserManageModel userManageModel = new UserManageModel();

			var list = userManager.Users.Select(_ => new UserManageModel
			{
				UserId = _.Id,
				UserName = _.Email,
			}).ToList();

			foreach (var user in list)
			{
				user.IsAdmin = userManager.GetRoles(user.UserId).Any(_ => _.Equals("Admin"));
			}
			return View(list);
		}
	}
}

UserAwards/UserAwards/Controllers/testController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UserAwards.Controllers
{
    public class testController : Controller
    {
        //
        // GET: /test/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /test/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /test/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /test/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /test/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /test/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /test/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /test/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

UserAwards/UserAwards/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - My ASP.NET MVC Application</title>
	<link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
	<style>
		.modal-content {
			width: 600px;
			margin: 30px;
		}
	</style>

</head>
<body>

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/jqueryval")
	@Scripts.Render("~/bundles/modernizr")
	@Scripts.Render("~/bundles/bootstrap")
	@Styles.Render("~/Content/css")

@RenderSection("scriptStile", false)

<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li>@Html.ActionLink("Awards of person", "Index", "PersonLinkAward")</li>
				<li>@Html.ActionLink("Persons", "Index", "Person")</li>
				<li>@Html.ActionLink("Awards", "Index", "Award")</li>
				<li>@Html.ActionLink("Test error page", "TestError", "Error")</li>
				<li>@Html.ActionLink("UserModel", "Index", "UserManage")</li>

			</ul>
			@Html.Partial("_LoginPartial")
		</div>
	</div>
</div>


@if ((ViewContext.RouteData.Values["controller"].ToString().ToLower() != "Award") &&
     (ViewContext.RouteData.Values["controller"].ToString().ToLower() != "Person"))
{
	<ol class="breadcrumb">
		<li>
			@Html.ActionLink("Person Award", "Index", "PersonLinkAward")
		</li>
		<li>
			@Html.ActionLink(ViewContext.RouteData.Values["controller"].ToString(), "Index", ViewContext.RouteData.Values["controller"].ToString())
		</li>

		@if (ViewContext.RouteData.Values["action"]!=null && 
			!string.IsNullOrEmpty(ViewContext.RouteData.Values["action"].ToString()) 
			&& ViewContext.RouteData.Values["action"].ToString() != "Index")
		{
			<li class="active">
				@Html.ActionLink(ViewContext.RouteData.Values["action"].ToString(), ViewContext.RouteData.Values["action"].ToString())
			</li>
		}
	</ol>
}

<div class="container body-content">
	@RenderBody()
	<hr/>
	<footer>
		<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
	</footer>
</div>

@RenderSection("scripts", required: false)
</body>
</html>

UserAwards/UserAwards/Views/Shared/_LayoutAward.cshtml
@{
	ViewBag.Title = "_LayoutAward";
	Layout = "~/Views/Shared/_Layout.cshtml";
}


@section scriptStile {
	<style>
		body {
			background: darkgray; /* Цвет фона */
			color: mediumblue; /* Цвет текста */
		}
	</style>
}

<div>
	@RenderBody()
</div>

UserAwards/UserAwards/Views/Shared/_LayoutPerson.cshtml
@{
	ViewBag.Title = "_LayoutPerson";
	Layout = "~/Views/Shared/_Layout.cshtml";
}



@section scriptStile {
	<style>
		body {
			background: darkgrey; /* Цвет фона */
			color: green; /* Цвет текста */
		}
	</style>
}

<div>
	@RenderBody()
</div>

UserAwards/UserAwards/Views/Shared/_ModalContentPartial.cshtml
@model UserAwards.Models.AwardModel

<div class="modal fade" id="myModal" role="dialog">
	<div class="modal-dialog">

		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">Award info</h4>
			</div>
			<div class="modal-body">
				<div class="editor-field">
					@Html.DisplayFor(model => model.Title)
				</div>
				
				<div class="editor-field">
					@Html.DisplayFor(model => model.Description)
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>

UserAwards/UserAwards/Views/Shared/_test.cshtml
@{
    ViewBag.Title = "_test";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>_test</h2>